controllers:
    resource: ../src/Controller/
    type: annotation

controllers_v1:
    resource: ../src/Controller/Api/v1
    type: annotation
    prefix: '/v1'

api_login_check:
    path: /v1/login

kernel:
    resource: ../src/Kernel.php
    type: annotation
